reactor/reactor-pool

src/main/java/reactor/pool/AbstractPool.java
src/main/java/reactor/pool/AffinityPool.java
src/main/java/reactor/pool/AllocationStrategies.java
src/main/java/reactor/pool/AllocationStrategy.java
src/main/java/reactor/pool/InstrumentedPool.java
src/main/java/reactor/pool/PoolBuilder.java
src/main/java/reactor/pool/SimplePool.java
src/test/java/reactor/pool/AllocationStrategiesTest.java
src/test/java/reactor/pool/CommonPoolTest.java

The idea in this PR is to expose internal state of the pool through a PoolMetrics API (similar to what is done with PooledRef, a view of the Pool).
It also exposes 2 configuration elements (max size and max pending size).
Fixes #22

Add InstrumentedPool notion and gauge-compatible metrics API

---

src/main/java/reactor/pool/AffinityPool.java
src/test/java/reactor/pool/CommonPoolTest.java

If one tries to obtain the metrics like the code below, they are not accurate (e.g. `acquired=1` and `idle=0`)
```
PooledRef.release
.subscribe(null, null, () -> {
pool.metrics().acquiredSize()
pool.metrics().idleSize()
})
```

Ensure metrics are accurate when PooledRef#release onComplete event is sent

---

src/main/java/reactor/pool/AbstractPool.java
src/main/java/reactor/pool/AffinityPool.java
src/main/java/reactor/pool/Pool.java
src/main/java/reactor/pool/SimplePool.java
src/test/java/reactor/pool/CommonPoolTest.java

currently adds an `acquire(Duration)` overload, we might want an `acquireInScope` too.
The way it is implemented is by starting the timer by default just before invoking `doAcquire`, then stopping it when we get a permit or find an available element.

fix #34 Acquire with max pending duration timeout

---

src/main/java/reactor/pool/AffinityPool.java
src/main/java/reactor/pool/SimplePool.java
src/test/java/reactor/pool/CommonPoolTest.java

Especially when fixed, invalidation needs to check for pending acquire.
Not doing it might prevent any further allocation.

fix #40 run drain loop after invalidation to check pending

---

build.gradle

Declare an Java9 JPMS Automatic-Module-Name for pool

---

build.gradle
src/main/java/reactor/pool/AffinityPool.java
src/main/java/reactor/pool/SimpleFifoPool.java
src/main/java/reactor/pool/SimpleLifoPool.java
src/main/java/reactor/pool/SimplePool.java

The need for MPMC queues for pending monos arises from the fact that
cancelling an acquire (with or without a timeout) now introduces
potential new concurrent consumers.

Switch to MPMC queues for pendings and remove JCTools

---

src/main/java/reactor/pool/AbstractPool.java
src/main/java/reactor/pool/AffinityPool.java
src/main/java/reactor/pool/PoolAcquirePendingLimitException.java
src/main/java/reactor/pool/PoolAcquireTimeoutException.java
src/main/java/reactor/pool/PoolShutdownException.java
src/main/java/reactor/pool/SimpleFifoPool.java
src/main/java/reactor/pool/SimpleLifoPool.java
src/main/java/reactor/pool/SimplePool.java
src/test/java/reactor/pool/CommonPoolTest.java

- `PoolAcquireTimeoutException` is still a `TimeoutException`,
but specialized (and which exposes a getter for the timeout).
- `PoolAcquirePendingLimitException` replaces a too generic
`IllegalStateException` and exposes the pending limit in a getter.
- `PoolShutdownException` replaces the way too generic `RuntimeException`
previously in place.

fix #49 Introduce reactor-pool specific exceptions

---

src/main/java/reactor/pool/AbstractPool.java
src/main/java/reactor/pool/DefaultPoolConfig.java
src/main/java/reactor/pool/PoolBuilder.java
src/main/java/reactor/pool/PoolConfig.java
src/main/java/reactor/pool/SimpleFifoPool.java
src/main/java/reactor/pool/SimpleLifoPool.java
src/main/java/reactor/pool/SimplePool.java
src/test/java/reactor/pool/CommonPoolTest.java
src/test/java/reactor/pool/PoolBuilderTest.java
src/test/java/reactor/pool/SimpleFifoPoolTest.java
src/test/java/reactor/pool/SimpleLifoPoolTest.java

This commit heavily reworks how the PoolBuilder is producing a PoolConfig
(internally) and then a concrete Pool instance.
The goal is to open the builder for cases where implementations would be
provided by external projects (eg. a netty event-loop aware implementation
for a project that pools netty connections).
One can pass a factory Function to the builder to create such a custom
pool, possibly also switching the builder to a custom type of configuration
beforehand. As a result, the DefaultPoolConfig has now been extracted as
PoolConfig and made public.
As a shorthand for the `build(Function)` that produces reactor-pool vanilla
implementations, we now expose `lifo()` and
`fifo()`, which are now the two out-of-the-box provided flavors.

fix #51 Expose PoolConfig, rework PoolBuilder with factory

---

src/main/java/reactor/pool/AllocationStrategies.java
src/main/java/reactor/pool/AllocationStrategy.java
src/main/java/reactor/pool/DefaultPoolConfig.java
src/main/java/reactor/pool/Pool.java
src/main/java/reactor/pool/PoolBuilder.java
src/main/java/reactor/pool/PoolConfig.java
src/main/java/reactor/pool/SimplePool.java
src/test/java/reactor/pool/AllocationStrategiesTest.java
src/test/java/reactor/pool/CommonPoolTest.java
src/test/java/reactor/pool/PoolBuilderTest.java
src/test/java/reactor/pool/SimpleFifoPoolTest.java
src/test/java/reactor/pool/SimpleLifoPoolTest.java

In progress: for now this focuses on the API, which is still called in a blocking fashion inside the constructor. Depends on #56.

fix #5 Remove blocking allocations in constructor and replace with warmup API

---

src/main/java/reactor/pool/AbstractPool.java
src/main/java/reactor/pool/DefaultPoolConfig.java
src/main/java/reactor/pool/NoOpPoolMetricsRecorder.java
src/main/java/reactor/pool/PoolBuilder.java
src/main/java/reactor/pool/PoolConfig.java
src/main/java/reactor/pool/PoolMetricsRecorder.java
src/main/java/reactor/pool/SimplePool.java
src/test/java/reactor/pool/CommonPoolTest.java
src/test/java/reactor/pool/TestUtils.java

This commit removes the responsibility of timestamping from the
PoolMetricsRecorder and puts it on a Clock instance that can be passed
to the PoolBuilder.
`now()` and `measureTime(long)` have been removed from the former, and
pool implementations now use the configured Clock instead. The default
clock is `Clock.SystemUTC()` (since only the millis() method is used).

fix #60 Separate Clock and PoolMetricsRecorder

---

gradle.properties

This is in preparation of `Dysprosium-RC1` release train.
Next pre and ga releases would be `0.1.0.RC1` and `0.1.0.RELEASE`.
Post merge tasks:

Mark stabilization of API by promoting version to 0.1.0

---

src/main/java/reactor/pool/AllocationStrategy.java
src/main/java/reactor/pool/DefaultPoolConfig.java
src/main/java/reactor/pool/InstrumentedPool.java
src/main/java/reactor/pool/Pool.java
src/main/java/reactor/pool/PoolBuilder.java
src/main/java/reactor/pool/PoolMetricsRecorder.java
src/main/java/reactor/pool/PooledRef.java

Standardize on not ending param and return descriptions with
a period and fix one little typo in metric docs.

Standardize docs and fix a typo

---

.gitignore
build.gradle
gradle.properties
gradle/setup.gradle

- use `maven-publish` and `com.jfrog.artifactory` plugins
- remove a few unneeded build aspects (dependencyManagement plugin,
pom manipulation to remove test scoped dependencies...)
- add groupId() task in preparation for a potential use of releaser
script
- choose artifactory repository depending on the version pattern
- optionally get artifactory credentials from project properties
artifactoryUsername and artifactoryPassword (both must be passed)

[build] Rework build for manual publications

---

src/main/java/reactor/pool/SimplePool.java
src/test/java/reactor/pool/CommonPoolTest.java

Invoking `drain()` when the allocator fails to create a resource will
trigger the acquire process for the pending requests.
Fixes #82

fix #82 Invoke drain() when the allocator fails

---

src/main/java/reactor/pool/SimplePool.java
src/test/java/reactor/pool/CommonPoolTest.java
src/test/java/reactor/pool/SimpleLifoPoolTest.java

This commit reworks the warmup code, enforcing it to run after the
main allocation, so that if there is a transient error it doesn't break
the FIFO/LIFO order.
Additionally it ensures that ACQUIRED is only decremented by the main
allocation, not the warmup. Permits are returned correctly as each of
the warmup fails.

fix #84 Prevent warmup from breaking the FIFO order

---

src/main/java/reactor/pool/AbstractPool.java
src/main/java/reactor/pool/PooledRefMetadata.java
src/test/java/reactor/pool/AbstractPoolRefTest.java
src/test/java/reactor/pool/CommonPoolTest.java
src/test/java/reactor/pool/TestUtils.java

Also [Polish] Split Clock out of InMemoryPoolMetrics, add 2 test Clocks

fix #89 Expose timestamps for allocation/release on PooledRefMetadata 

---

build.gradle
src/main/java/reactor/pool/introspection/SamplingAllocationStrategy.java
src/test/java/reactor/pool/introspection/SamplingAllocationStrategyTest.java

This pull request adds a utility `AllocationStrategy` to trace a sample of calls to `getPermits` and `returnPermits`.
The strategy lives in a newly introduced `introspection` package.

Add SamplingAllocationStrategy, in new introspection util package

---

build.gradle
src/test/java/reactor/pool/AcquireDefaultPoolTest.java
src/test/java/reactor/pool/AllocationStrategiesTest.java
src/test/java/reactor/pool/CommonPoolTest.java
src/test/java/reactor/pool/PendingAcquireLifoBehaviorTest.java
src/test/java/reactor/pool/TestUtils.java

This commit polishes the tests, and notably how ParameterizedTest are
reported in console/CI. Currently, the method names are omitted which
makes parsing the logs for eg. CommonPoolTest very complicated. This
is because the default name pattern fo a ParameterizedTest only
includes the index and parameter values (sic). By adding the
{displayName} placeholder (explicitly or via the meta-annotation we
introduce), we get the method name by default.
- Bump JUnit 5.6.0 => 5.7.1
- Nested test class can now be static
- Add ParameterizedTestWithName meta-annotation, ensure test method
always shown

Polish ParameterizedTest reports

---

src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java
src/main/java/reactor/pool/SimpleDequePool.java
src/test/java/reactor/pool/CommonPoolTest.java

This commit reworks the whole SimpleDequePool#drainLoop, simplifying
the pendingOffer implementation along the way.
By evaluating the `pending` queue size inside the drain loop, we can
more safely ensure that we detect all the pending borrowers that should
be failed fast due to going over the `maxPending` limit, while still
correctly taking into account the available permits (and the borrowers
that have effectively been served via newly permitted allocations).
The `AbstractPool.PENDING_COUNT` field is now purely used for stats and
reflects the queue size after the drain loop has matched incoming
borrowers with resources, and the borrowers past maxPending have been
culled. This way, even though the stat method can be invoked while the
drain loop is being executed, it will see an outdated …

Rework drainLoop so that extra pending acquires are better culled

---

build.gradle

This is a backport of commits a2446d4 and 956a0b2.
See reactor/reactor#695.

[backport] Remove jcenter from build in 0.1.x

---

src/test/java/reactor/pool/CommonPoolTest.java

The test would log an `ErrorCallbackNotImplemented` but the error is
actually evaluated in a `doOnError`, so we can suppress this output
by subscribing with an empty error handler.
Fixes #125.

Make log quieter in CommonPoolTest#pendingLimitAsync

---

src/main/java/reactor/pool/InstrumentedPool.java
src/main/java/reactor/pool/SimpleDequePool.java
src/test/java/reactor/pool/CommonPoolTest.java

This commit ensures the acquiredSize() metric is only updated when the
resource has been allocated, and is about to be handed off to the
subscriber of acquire().
The decrement in case of allocation error is thus not needed anymore.
Fixes #126.

Only increment acquiredSize() once resource has been allocated

---

.github/workflows/ci.yml
.github/workflows/publish.yml
gradle/releaser.gradle
gradle/setup.gradle

This commit changes the release process to be based on GitHub Actions.
CI is already performed on GHA, but that workflow will now only run
for pull_request trigger.
We define helper tasks and methods in the setup.gradle file to help
interpret the version number. The trigger is pushing a commit to an
active maintenance branch.
The new workflow uses GitHub Environments to manage access to secrets,
especially in the case of milestones and releases as it introduces
signing of artifacts in these cases. It is split into 4 jobs, 3 of
which are conditional and depend on a GitHub Environment.
Notably:
- Add a function to qualify a version number as one of RELEASE,
MILESTONE, SNAPSHOT or BAD
- Add a GitHub Actions oriented task, `qualifyVersionGha`, which
produces gha step output for the current …

GitHub Actions Release Process: signing, artifactory, sonatype

---

build.gradle

This is because types from reactor-code leak in the signature of
reactor-pool, so should be marked as API.
As a consequence, the published pom will use compile instead of
runtime.

Use api dependency for core, ie compile scope in pom

---

build.gradle
gradle.properties
src/main/java/reactor/pool/AbstractPool.java
src/main/java/reactor/pool/InstrumentedPool.java
src/main/java/reactor/pool/SimpleDequePool.java
src/test/java/reactor/pool/SimpleDequePoolInstrumentationTest.java

This commit adds inactivity insights to the InstrumentedPool interface,
allowing to get a sense of how long a pool has been inactive for.
secondsSinceLastInteraction() returns a long representing the number of
seconds since the last recorded interaction, which currently includes
explicitly background eviction, warmup, maybeRecycleAndDrain, pool
disposeLater and any interaction that ends up executing the drainLoop.
Additionally, isInactiveForMoreThan(Duration) convenience method is
also provided.
Fixes #134.

Add inactivity insights (secondsSinceLastInteraction)

---

src/main/java/reactor/pool/AbstractPool.java
src/main/java/reactor/pool/SimpleDequePool.java
src/test/java/reactor/pool/CommonPoolTest.java

In the case of a call to `release()`:
- The Mono now only completes once the destroy process has itself
completed, eg. in case the eviction predicate triggers invalidation.
- Exception in applying the releaseHandler will be propagated to the
subscriber, wrapped in an IllegalStateException
- Exception in applying the destroyHandler will be propagated to the
subscriber directly IF this is part of the natural release -> evict
path, or wrapped in an IllegalStateException if following an error
in applying the releaseHandler
In the case of a call to `invalidate()`:
- Exception in applying the destroyHandler will be propagated directly
to the subscriber
In the case of background eviction, exceptions in applying the
destroyHandler will be simply logged.
Additionally, this commit ensures that …

Better handle exceptions in releaseHandler/destroyHandler

---

build.gradle
codequality/spotless/licenseSlashstarStyle.txt
src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java
src/main/java/reactor/pool/AbstractPool.java
src/main/java/reactor/pool/AllocationStrategies.java
src/main/java/reactor/pool/AllocationStrategy.java
src/main/java/reactor/pool/DefaultPoolConfig.java
src/main/java/reactor/pool/InstrumentedPool.java
src/main/java/reactor/pool/NoOpPoolMetricsRecorder.java
src/main/java/reactor/pool/PoolMetricsRecorder.java
src/main/java/reactor/pool/PooledRefMetadata.java
src/main/java/reactor/pool/introspection/SamplingAllocationStrategy.java
src/test/java/reactor/pool/AbstractPoolRefTest.java
src/test/java/reactor/pool/AllocationStrategiesTest.java
src/test/java/reactor/pool/CommonPoolTest.java
src/test/java/reactor/pool/PendingAcquireLifoBehaviorTest.java
src/test/java/reactor/pool/SimpleDequePoolInstrumentationTest.java
src/test/java/reactor/pool/TestUtils.java
src/test/java/reactor/pool/introspection/SamplingAllocationStrategyTest.java

To be merged with rebase.
Follow up both #141 and #143.
﻿- [polish] Use YEAR variable instead of range in license template (#144)
- [polish] Allow Spotless without ratchet with spotlessFrom=ALL (#144)
- [chores] Fix start year of some copyright notice headers (#144)

Refine spotless configuration and copyright ranges

---

src/main/java/reactor/pool/AbstractPool.java
src/main/java/reactor/pool/PooledRef.java
src/main/java/reactor/pool/SimpleDequePool.java
src/test/java/reactor/pool/CommonPoolTest.java

This commit improves the guarding of calling #invalidate() on a ref that
has already been released.
It prevents the acquireCount metric to go below zero in such a case.
The current state of the codebase would make it difficult to allow an
invalidate() call on the same ref #release() was called on.
When an invalidate() would have been desirable post-release, the
background eviction feature should suffice.
However, this aspect was not made that explicit in the javadoc, which
has been amended to better reflect the constraints between the various
PooledRef methods.
See #146.

Correctly guard invalidate() usage vs release(), fix acquireCount

---

src/main/java/reactor/pool/AbstractPool.java
src/main/java/reactor/pool/Pool.java
src/test/java/reactor/pool/CommonPoolTest.java

This commit adds an accessor for the immutable PoolConfig of pools.
The default version throws an `UnsupportedOperationException`, but all implementors will be required to override this in a future release (1.0.0 most likely).

Add config() accessor to Pool

---

src/main/java/reactor/pool/PoolBuilder.java
src/main/java/reactor/pool/PoolShutdownException.java
src/main/java/reactor/pool/decorators/GracefulShutdownInstrumentedPool.java
src/main/java/reactor/pool/decorators/InstrumentedPoolDecorators.java
src/test/java/reactor/pool/decorators/GracefulShutdownInstrumentedPoolTest.java
src/test/java/reactor/pool/decorators/InstrumentedPoolDecoratorsTest.java

Work in progress.
This decorates any `InstrumentedPool`, returning an instance that adds `gracefulShutdown` method.
Using wrappers, it tracks acquired and acquiring calls and prevents further acquiring once graceful shutdown has started.
After that, is enough `release()` are made or if the timeout triggers, the pool is shut down for good.
Fixes #148

Introduce decorators, add GracefulShutdown feature as decorator

---

src/test/java/reactor/pool/decorators/GracefulShutdownInstrumentedPoolTest.java

This commit fixes disposeGracefullyTwiceWithActualTimeoutWaitForSameTime
flaky test by reworking how the disposeGracefully monos are triggered
and reworking the assertion to show that only the first delay is taken
into account.

Fix flaky disposeGracefullyTwice test

---

build.gradle
src/main/java/reactor/pool/AbstractPool.java
src/main/java/reactor/pool/DefaultPoolConfig.java
src/main/java/reactor/pool/PoolBuilder.java
src/main/java/reactor/pool/PoolConfig.java
src/test/java/reactor/pool/CommonPoolTest.java
src/test/java/reactor/pool/PoolBuilderTest.java

This is the PR to allow to configure the reactor-pool with a custom user timer service that can be used for pending acquisitions (thanks a lot to Simon for the help).
@simonbasle, **please do not merge for the moment**, because Violeta wants to investigate the timer issue before merging anything. And there is still the documentation to update; so, please do not review for the moment.
thanks !

Add PoolConfig#pendingAcquireTimer config option

---

build.gradle
gradle/libs.versions.toml

This commit improves the japicmp integration in the build:
1) Add a finalizedBy task that prints a filtered report
The basic text report uses * and ! as markers for binary and source
incompatible changes respectively. Additionally, a MODIFIED class is
marked with ***. This task attempts at pinpointing the incompatible
changes only in the report, and printing these lines.
This report is called out in the "how to fix" tip in the CI preliminary
step.
2) Ensure sourceModified changes are considered
See reactor/reactor#722.
If a change is binary compatible but not source compatible, using
`onlyBinaryCompatibleModified = true` will mask the issue. This
change uses `onlyModified = true` instead. This is slightly more
verbose, but this is alleviated by (1).
3) Update japicmp-gradle-plugin, …

Improve JapiCmp: avoid misses, improve reporting and exclusions

---

build.gradle
gradle.properties
gradle/doc.gradle
gradle/libs.versions.toml
gradle/setup.gradle
reactor-pool-micrometer/build.gradle
reactor-pool-micrometer/src/main/java/reactor/pool/introspection/micrometer/DocumentedPoolMeters.java
reactor-pool-micrometer/src/main/java/reactor/pool/introspection/micrometer/Micrometer.java
reactor-pool-micrometer/src/main/java/reactor/pool/introspection/micrometer/MicrometerMetricsRecorder.java
reactor-pool-micrometer/src/main/java/reactor/pool/introspection/micrometer/PoolGaugesBinder.java
reactor-pool-micrometer/src/main/java/reactor/pool/introspection/micrometer/package-info.java
reactor-pool-micrometer/src/test/java/reactor/pool/introspection/micrometer/MicrometerTest.java
reactor-pool/build.gradle
settings.gradle

This commit adds a new module depending directly on Micrometer which
provides out-of-the-box implementations of PoolMetricsRecorder and other
utilities to instrument a Pool with Micrometer.
Fixes #161.

Add `reactor-pool-micrometer` module with recorder and gauges

---

.github/workflows/ci.yml
.github/workflows/publish.yml
gradle/setup.gradle

This commit changes the way job output is defined, using the new way of
a GITHUB_OUTPUT file environment variable.
The old way of echoing strings is deprecated for sensitive elements,
including action/job output.
It also reorders the output in order to:
• ensure BAD version is detected before any output and fails the job
• ensure only one version/versionType is outputted when there are
multiple modules (here, the `reactor-pool` one)
Finally it updates core and gradle actions to latest versions.
This fixes warnings about deprecated output style and deprecated Node
version being still in use by these actions.
See reactor/reactor#727.

Use new gha API for setting output, latest core actions

---

reactor-pool/src/main/java/reactor/pool/InstrumentedPool.java
reactor-pool/src/test/java/reactor/pool/InstrumentedPoolPoolMetricsTest.java

Previously the units were mixed up and milliseconds were directly compared to seconds.
Fixes #176.

Fix time unit mixup in `InstrumentedPool.PoolMetrics#isInactiveForMoreThan` default implementation

---

reactor-pool-micrometer/src/main/java/reactor/pool/introspection/micrometer/MicrometerMetricsRecorder.java
reactor-pool-micrometer/src/main/java/reactor/pool/introspection/micrometer/PoolMetersDocumentation.java
reactor-pool-micrometer/src/test/java/reactor/pool/introspection/micrometer/MicrometerTest.java
reactor-pool/src/main/java/reactor/pool/AbstractPool.java
reactor-pool/src/main/java/reactor/pool/NoOpPoolMetricsRecorder.java
reactor-pool/src/main/java/reactor/pool/PoolMetricsRecorder.java
reactor-pool/src/main/java/reactor/pool/SimpleDequePool.java
reactor-pool/src/test/java/reactor/pool/CommonPoolTest.java
reactor-pool/src/test/java/reactor/pool/TestUtils.java

This is related to https://github.com/reactor/reactor-netty/issues/2946

Expose metrics for `pending acquire` operation latency

---

reactor-pool/src/main/java/reactor/pool/SimpleDequePool.java
reactor-pool/src/test/java/reactor/pool/CommonPoolTest.java

This fixes a regression that comes from #171, from 1.0.1 version: 
since the pool warmup method allows to be called at anytime, then if no more permits are available from the allocation strategy, the Flux.merge method is then called with a `mergeConcurrency`pameter that is set to `0`, causing the following exception:
```
maxConcurrency > 0 required but it was 0
java.lang.IllegalArgumentException: maxConcurrency > 0 required but it was 0
at reactor.core.publisher.FluxFlatMap.<init>(FluxFlatMap.java:74)
at reactor.core.publisher.Flux.merge(Flux.java:1406)
at reactor.core.publisher.Flux.merge(Flux.java:1375)
```
Added a check in warmup to immediately return in case no permits are available.
Also added a test case.
Fixes #180

Warmup throws IllegalArgumentException in case no permits are available

---

.github/workflows/ci.yml
.github/workflows/publish.yml

`Node.js 16` actions are deprecated. Please update the following actions to use `Node.js 20`: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8, actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Update `GitHub Actions` versions in order to avoid using `Node.js 16`

---

reactor-pool/src/main/java/reactor/pool/AbstractPool.java
reactor-pool/src/test/java/reactor/pool/CommonPoolTest.java

recordPendingSuccess/FailureAndLatency seems not recorded properly without timeout.
If we call acquire() without timeout, timeoutTask remain as TIMEOUT_DISPOSED since AbstractPool#430 check if pendingAcquireTimeout is non-zero.

Fix recordPendingSuccess/FailureAndLatency not recorded without timeout

---

reactor-pool/src/main/java/reactor/pool/AbstractPool.java
reactor-pool/src/main/java/reactor/pool/SimpleDequePool.java
reactor-pool/src/test/java/reactor/pool/CommonPoolTest.java

When applying `pendingAcquireTimeout`, check for current pending Borrowers

---

reactor-pool/src/main/java/reactor/pool/AbstractPool.java

Hello Team,
I observed a formatting issue where the interface "InstrumentedPool.PoolMetrics" was formatted  on a second line for the AbstractPool class.
As per my eyes, it seemed inconvenient and hence suggested a fix for the same.
Kindly let me know your thoughts on this formatting suggestion.

Format fix for PooMetrics interface inside AbstractPool.java

---

.github/workflows/ci.yml

Using the action to execute Gradle via the `arguments` parameter is deprecated https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated

Remove `gradle/actions/setup-gradle` deprecated functionality

---

reactor-pool/src/main/java/reactor/pool/PoolBuilder.java
reactor-pool/src/main/java/reactor/pool/SimpleDequePool.java

Annotate with `Nullable`, fields that can become null

---

gradle/wrapper/gradle-wrapper.properties

According to the documentation the command below should be used for upgrade 
`./gradlew wrapper --gradle-version=8.14.1 && ./gradlew wrapper`

Bump `Gradle` to version `8.14.1`
